### ISSUE TITLE
suggest parentheses around comparison in operand of '^' [-Wparentheses]

### ISSUE THREAD

**Issue by joelrader** [pkourany/SeeedRFID_IDE#1]
Veryfing code using this library in Particle Build fails with this error:

```

```

In file included from ../inc/spark_wiring.h:29:0,
                 from ../inc/application.h:29,
                 from SeeedRFID/SeeedRFID.h:55,
                 from SeeedRFID/SeeedRFID.cpp:52:
This looks like an error in SeeedRFID library. Would you like to create an issue on GitHub to let the author know?
CREATE ISSUE
../../core-common-lib/SPARK_Firmware_Driver/inc/config.h:12:2: warning: #warning "Defaulting to Release Build" [-Wcpp]
 #warning  "Defaulting to Release Build"
  ^

SeeedRFID/SeeedRFID.cpp: In member function 'bool SeeedRFID::checkBitValidationUART()':
SeeedRFID/SeeedRFID.cpp:83:42: warning: suggest parentheses around comparison in operand of '^' [-Wparentheses]
  if( 5 == _data.dataLen && (_data.raw[4] == _data.raw[0]^_data.raw[1]^_data.raw[2]^_data.raw[3]))
                                          ^
In file included from ../inc/spark_wiring.h:29:0,
                 from ../inc/application.h:29,
                 from rfid_uart.cpp:2:
../../core-common-lib/SPARK_Firmware_Driver/inc/config.h:12:2: warning: #warning "Defaulting to Release Build" [-Wcpp]
 #warning  "Defaulting to Release Build"
  ^
rfid_uart.cpp: In function 'void setup()':
rfid_uart.cpp:22:14: warning: unused variable 'tag' [-Wunused-variable]
 void setup() {
              ^

rfid_uart.cpp: In function 'void loop()':
rfid_uart.cpp:26:5: error: 'RFID' was not declared in this scope
  SeeedRFID RFID(RFID_RX_PIN, RFID_TX_PIN); // This must be in setup, not before
     ^

rfid_uart.cpp:31:3: error: 'tag' was not declared in this scope
  if(RFID.isAvailable()){
   ^

make: **\* [rfid_uart.o] Error 1

**Comment by pkourany** [comment]
Done!
