### ISSUE TITLE
RFID Constructor must be in Setup(), otherwise it hard faults Spark Core

### ISSUE THREAD

**Issue by joelrader** [pkourany/SeeedRFID_IDE#2]
SeeedRFID RFID(RFID_RX_PIN, RFID_TX_PIN); // Must be in Setup(){}

**Comment by pkourany** [comment]
Thanks @raiderj.  I fix that and add support for the Photon as well and then publish an updated version.

**Comment by joelrader** [comment]
Fantastic! Really appreciate the initial steps to put the code online :-)

**Comment by pkourany** [comment]
Done!
